"""empty message

Revision ID: 194ac80ebd90
Revises: 
Create Date: 2023-10-25 14:16:59.856644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194ac80ebd90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_table'))
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_table')),
    sa.UniqueConstraint('email', name=op.f('uq_user_table_email')),
    sa.UniqueConstraint('password', name=op.f('uq_user_table_password')),
    sa.UniqueConstraint('username', name=op.f('uq_user_table_username'))
    )
    op.create_table('expense_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category_table.id'], name=op.f('fk_expense_table_category_id_category_table')),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_expense_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_table')
    op.drop_table('user_table')
    op.drop_table('category_table')
    # ### end Alembic commands ###
