"""empty message

Revision ID: 6672dfb55929
Revises: 194ac80ebd90
Create Date: 2023-11-02 14:06:36.332541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6672dfb55929'
down_revision = '194ac80ebd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_table', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_table', 'paid')
    # ### end Alembic commands ###
