"""empty message

Revision ID: 78271906f842
Revises: 6672dfb55929
Create Date: 2023-11-08 19:33:28.934762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78271906f842'
down_revision = '6672dfb55929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_table', sa.Column('category_name', sa.String(), nullable=False))
    op.create_foreign_key(op.f('fk_expense_table_category_name_category_table'), 'expense_table', 'category_table', ['category_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_expense_table_category_name_category_table'), 'expense_table', type_='foreignkey')
    op.drop_column('expense_table', 'category_name')
    # ### end Alembic commands ###
